version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: ai_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  vision_pipeline:
    build: ./services/vision_pipeline
    container_name: ai_vision
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./data/videos:/data/videos
      - ./data/frames:/data/frames
    depends_on:
      - redis

  object_review:
    build: ./services/object_review
    container_name: ai_object_review
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./data/review:/app/data

  control:
    build: ./services/control
    container_name: ai_control
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./data/control:/app/data

  ui:
    build: ./services/ui
    container_name: ai_ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data/results:/app/results
    depends_on:
      - control


  llm_summarizer:
    build: ./services/llm_summarizer
    container_name: ai_llm
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./data/results:/app/results
