version: '3.8'

services:

  redis:
    image: redis:7
    container_name: media-redis
    ports:
      - "6379:6379"
    networks:
      - media-net

  vector_db:
    image: qdrant/qdrant
    container_name: media-qdrant
    ports:
      - "6333:6333"
    networks:
      - media-net
    volumes:
      - qdrant_data:/qdrant/storage

  streamlit_ui:
    build:
      context: ./services/ui
    container_name: media-ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - media-net

  vision_pipeline:
    build:
      context: ./services/vision_pipeline
    container_name: media-vision
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - media-net
    command: tail -f /dev/null  # Dummy für Entwicklung

  control:
    build:
      context: ./services/control
    container_name: media-control
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - media-net
    command: tail -f /dev/null  # Steuerung/LLM/Scheduler später hier

networks:
  media-net:

volumes:
  qdrant_data:
