
# Additional AI Modules

  pose_estimation:
    build: ./services/pose_estimation
    container_name: ai_pose_estimation
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./data/results:/app/results
    

  ocr_detection:
    build: ./services/ocr_detection
    container_name: ai_ocr_detection
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./data/results:/app/results
    

  clip_nsfw:
    build: ./services/clip_nsfw
    container_name: ai_clip_nsfw
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./data/results:/app/results
    

  face_reid:
    build: ./services/face_reid
    container_name: ai_face_reid
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./data/results:/app/results
    

  whisper_transcriber:
    build: ./services/whisper_transcriber
    container_name: ai_whisper_transcriber
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./data/results:/app/results
    